### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kkoemna** [kkoemna/furima-38481#20]
# 自身のフリマアプリのURL
https://furima-38481.onrender.com/

# Basic認証のIDとパスワード
admin / 2222

# 出品者用のメールアドレスとパスワード
seller@test.com / seller00

# 購入者用のメールアドレスとパスワード
buyer@test.com / buyer00

**Comment by motomuun** [comment]
@kkoemna さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品編集機能の確認**

- [x] **必要な情報を適切に入力して「変更する」ボタンを押すと、商品情報（商品画像・商品名・商品の状態など）を編集できること**
「商品の説明」が編集できません。編集できるように修正をお願いします。

- [x] **商品名やカテゴリーの情報など、すでに登録されている商品情報は商品情報編集画面を開いた時点で表示されること（商品画像・販売手数料・販売利益に関しては、表示されない状態で良い）**
「商品の説明」が空欄になっています。編集画面を開いた時点で表示されるように修正をお願いします。



修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by kkoemna** [comment]
レビューありがとうございます。
修正依頼箇所2点を修正し、本番環境で動作確認を行いました。
単純なスペルミスでした。
再度データベースをリセットして、ユーザー作成しています。
ご確認をお願いします。

**Comment by ghost** [comment]
@kkoemna さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

`本メッセージ内で、今後の学習についてご案内しています。必ず確認するようにしてください。`

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

------------------------------------------------------------------------------------------
◆ 今後の流れについてのご案内（※詳細は下記リンクのガイダンス資料参照）
------------------------------------------------------------------------------------------
◎この後の期間では、以下のアクションが必要となります。
・最終課題説明文の作成・提出
・FURIMAへの追加機能の実装 または オリジナルアプリ開発
・上記の開発に関する要件定義書の提出
・履歴書と職務経歴書の作成・提出（転職サポートありの方）
・学習成果発表会の準備

◎下記リンク先の「**追加実装・オリジナルアプリ開発 ガイダンス資料**」を必ずご確認ください。
**https://master.tech-camp.in/v2/curriculums/7839**

------------------------------------------------------------------------------------------
◆ さいごに
------------------------------------------------------------------------------------------
◎ガイダンス資料を確認した上で、今後の流れについて不明点がございましたら、担当ライフコーチまでご相談ください。

◎いよいよ卒業までのラストスパートです。これまで頑張ってきたことをフル活用して、最大限の受講成果につなげていきましょう。
![最終課題LGTM](https://user-images.githubusercontent.com/116065064/213107483-a695384e-0faf-472a-b4d5-f32452d2bee1.png)
